# apphosting.yaml
kind: "AppStack"
apiVersion: "v1alpha"
runConfig:
  concurrency: 80
  cpu: 1
  memoryMiB: 512
# env:
#   - variable: STORAGE_CONNECTION_STRING
#     secret: "projects/pa-clinical-assessment/secrets/DATABASE_URL"
